package hu.taliann.icesmp.playerprofile.api;
import hu.taliann.icesmp.classspec.domain.*;import hu.taliann.icesmp.playerprofile.domain.*;import hu.taliann.icesmp.playerprofile.domain.section.*;import hu.taliann.icesmp.playerprofile.persistence.*;import java.util.*;import java.util.concurrent.*;
public final class PlayerProfileQueryService {
 private final PlayerProfileRepository repository;
 public PlayerProfileQueryService(PlayerProfileRepository repository){this.repository=Objects.requireNonNull(repository);}
 public CompletionStage<Optional<PlayerProfileSnapshot>> find(UUID id){return repository.find(id);}
 public CompletionStage<Optional<PlayerProfileSnapshot>> findByName(String name){if(name==null||name.isBlank())return CompletableFuture.completedFuture(Optional.empty());return repository.findByName(name);}
 public CompletionStage<Optional<ProfileSectionSnapshot<?>>> section(UUID id,ProfileSectionId section){return repository.loadSection(id,section);}
 public CompletionStage<PublicPlayerProfileDto> publicDto(UUID id){return required(id).thenApply(this::publicDto);}
 public CompletionStage<SelfPlayerProfileDto> selfDto(UUID id){return required(id).thenApply(this::selfDto);}
 public CompletionStage<AdminPlayerProfileDto> adminDto(UUID id){return required(id).thenApply(this::adminDto);}
 public PublicPlayerProfileDto publicDto(PlayerProfileSnapshot p){PreferenceSection pref=p.preferences().value();boolean visible=pref.publicProfile()&&p.identity().value().publicVisible();String faction=visible&&pref.publicClassFactionSpec()?p.faction().value().membershipId():"";ClassSpecSection cs=p.classSpec().value();String clazz=visible&&pref.publicClassFactionSpec()?cs.primaryClassId():"";String spec="";if(visible&&pref.publicClassFactionSpec()&&cs.activeSlot()!=null)spec=cs.loadout(cs.activeSlot()).specializationId();Set<String> achievements=visible&&pref.publicAchievements()?p.achievements().value().publicAchievements():Set.of();Map<String,Long> stats=visible?p.statistics().value().season():Map.of();String companion=visible&&pref.publicCompanion()?p.companions().value().activeCompanionId():"";return new PublicPlayerProfileDto(p.playerId(),visible,visible?p.identity().value().lastKnownName():"",faction,clazz,spec,achievements,stats,companion,p.profileRevision(),revisionMap(p),p.updatedAt());}
 public SelfPlayerProfileDto selfDto(PlayerProfileSnapshot p){PreferenceSection pref=p.preferences().value();Map<String,String> values=new LinkedHashMap<>(pref.values());values.put("language",pref.language());values.put("hud-enabled",Boolean.toString(pref.hudEnabled()));values.put("scoreboard-enabled",Boolean.toString(pref.scoreboardEnabled()));values.put("notifications-enabled",Boolean.toString(pref.notificationsEnabled()));return new SelfPlayerProfileDto(publicDto(p),p.economy().value().wallets(),p.economy().value().bankBalance(),p.quests().value().active(),p.quests().value().completed(),p.spellbook().value().provenance(),p.spellbook().value().selectedSpell(),p.spellbook().value().favorites(),p.spellbook().value().mastery(),p.professions().value().experience(),p.professions().value().levels(),values,p.quests().value().claimableRewards());}
 public AdminPlayerProfileDto adminDto(PlayerProfileSnapshot p){Map<String,String> health=new LinkedHashMap<>(),evidence=new LinkedHashMap<>(),ops=new LinkedHashMap<>();p.sectionMap().forEach((id,s)->{health.put(id.id(),s.health().status().name());if(!s.health().evidenceId().isBlank())evidence.put(id.id(),s.health().evidenceId());});p.operations().value().operations().forEach((id,o)->ops.put(id,o.status().name()));ModerationSection m=p.moderation().value();return new AdminPlayerProfileDto(selfDto(p),p.health().status().name(),health,evidence,ops,m.activePunishmentRefs(),m.strikeCount(),m.adminNoteRefs(),m.auditState());}
 private static Map<String,Long> revisionMap(PlayerProfileSnapshot p){LinkedHashMap<String,Long> m=new LinkedHashMap<>();p.sectionRevisions().entrySet().stream().sorted(Map.Entry.comparingByKey()).forEach(e->m.put(e.getKey().id(),e.getValue().revision()));return m;}
 private CompletionStage<PlayerProfileSnapshot> required(UUID id){return repository.find(id).thenCompose(found->found.<CompletionStage<PlayerProfileSnapshot>>map(CompletableFuture::completedFuture).orElseGet(()->CompletableFuture.failedFuture(new NoSuchElementException("player profile not found"))));}
}
