[versions]
minecraft = "1.21.11"
folia-api = "1.21.11-R0.1-SNAPSHOT"
run-paper = "2.3.1"

run-task = "3.0.2"

[libraries]
folia-api = { module = "dev.folia:folia-api", version.ref = "folia-api" }

[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }
