package hu.taliann.icesmp.listeners;

import net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializer;
import org.bukkit.Bukkit;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.util.HexFormat;
import java.util.List;
import java.util.Locale;
import java.util.Properties;
import java.util.UUID;

/**
 * Sends the IceSMP pack through Paper/Folia's additive resource-pack API.
 *
 * <p>The bundled {@code resource-pack.properties} is generated by the R2 publishing workflow and
 * therefore follows the plugin JAR instead of being copied once into the server data directory.
 * Operators may still use the explicit {@code override-url}/{@code override-sha1} config keys for
 * emergency rollback or staging. A stable UUID represents the IceSMP layer across pack versions,
 * so a newer pack replaces this layer without removing packs supplied by the server or other
 * plugins.</p>
 */
public final class ResourcePackListener implements Listener {

    private static final String CONFIG_ROOT = "resource-pack.";
    private static final String METADATA_RESOURCE = "resource-pack.properties";
    private static final UUID DEFAULT_PACK_ID = UUID.fromString("7c847f1e-d942-3c8f-bd46-5c43bb1a3e67");

    private final JavaPlugin plugin;
    private volatile PackRequest request;

    public ResourcePackListener(final JavaPlugin plugin) {
        this.plugin = plugin;
        reload();
    }

    @EventHandler(priority = EventPriority.MONITOR)
    public void onJoin(final PlayerJoinEvent event) {
        send(event.getPlayer());
    }

    /** Reloads config/metadata and safely re-sends the current layer to every online player. */
    public void reloadAndResend() {
        reload();
        for (final Player player : List.copyOf(Bukkit.getOnlinePlayers())) {
            player.getScheduler().run(plugin, task -> send(player), null);
        }
    }

    /** Reloads only the immutable request snapshot; invalid configuration disables delivery. */
    public void reload() {
        this.request = loadRequest();
    }

    /** Sends the validated snapshot. This method must run on the player's owning region thread. */
    public void send(final Player player) {
        final PackRequest current = request;
        if (current == null) {
            return;
        }
        try {
            player.addResourcePack(current.id(), current.url(), current.hash(), current.prompt(), current.required());
        } catch (final IllegalArgumentException exception) {
            plugin.getLogger().warning("Az IceSMP resource pack nem küldhető ki: " + exception.getMessage());
        }
    }

    private PackRequest loadRequest() {
        final FileConfiguration config = plugin.getConfig();
        if (!config.getBoolean(CONFIG_ROOT + "enabled", true)) {
            plugin.getLogger().info("IceSMP resource-pack küldés kikapcsolva.");
            return null;
        }

        final Properties metadata = loadBundledMetadata();
        if (metadata == null) {
            return null;
        }

        final String url = overrideOrMetadata(config, "override-url", metadata, "url");
        final String sha1 = overrideOrMetadata(config, "override-sha1", metadata, "sha1")
                .toLowerCase(Locale.ROOT);
        if (url.isEmpty() || sha1.isEmpty()) {
            plugin.getLogger().warning("A resource pack nincs kiküldve: hiányos a beépített URL/SHA-1 metadata.");
            return null;
        }

        final URI parsedUrl;
        try {
            parsedUrl = URI.create(url);
        } catch (final IllegalArgumentException exception) {
            plugin.getLogger().warning("Érvénytelen resource-pack URL: " + url);
            return null;
        }
        if (!"https".equalsIgnoreCase(parsedUrl.getScheme()) || parsedUrl.getHost() == null
                || !StandardCharsets.US_ASCII.newEncoder().canEncode(url)) {
            plugin.getLogger().warning("A resource-pack URL-nek ASCII HTTPS URL-nek kell lennie: " + url);
            return null;
        }

        if (!sha1.matches("[0-9a-f]{40}")) {
            plugin.getLogger().warning("Érvénytelen resource-pack SHA-1 (40 kisbetűs hex karakter szükséges): " + sha1);
            return null;
        }
        final byte[] hash = HexFormat.of().parseHex(sha1);

        final String configuredId = config.getString(CONFIG_ROOT + "id", DEFAULT_PACK_ID.toString()).trim();
        final UUID packId;
        try {
            packId = UUID.fromString(configuredId);
        } catch (final IllegalArgumentException exception) {
            plugin.getLogger().warning("Érvénytelen resource-pack.id UUID: " + configuredId);
            return null;
        }

        final String rawPrompt = config.getString(CONFIG_ROOT + "prompt",
                "&bAz IceSMP egyedi modelljeihez és felületéhez szükséges resource pack.");
        final String prompt = LegacyComponentSerializer.legacySection().serialize(
                LegacyComponentSerializer.legacyAmpersand().deserialize(rawPrompt));
        final boolean required = config.getBoolean(CONFIG_ROOT + "required", true);

        plugin.getLogger().info("IceSMP resource pack előkészítve: " + sha1 + " (" + url + ")");
        return new PackRequest(packId, url, hash, prompt, required);
    }

    private Properties loadBundledMetadata() {
        try (InputStream stream = plugin.getResource(METADATA_RESOURCE)) {
            if (stream == null) {
                plugin.getLogger().warning("Hiányzik a JAR-ból a " + METADATA_RESOURCE + " fájl.");
                return null;
            }
            final Properties properties = new Properties();
            properties.load(new InputStreamReader(stream, StandardCharsets.UTF_8));
            return properties;
        } catch (final IOException exception) {
            plugin.getLogger().warning("A resource-pack metadata nem olvasható: " + exception.getMessage());
            return null;
        }
    }

    private String overrideOrMetadata(final FileConfiguration config, final String overrideKey,
                                      final Properties metadata, final String metadataKey) {
        final String override = config.getString(CONFIG_ROOT + overrideKey, "").trim();
        return override.isEmpty() ? metadata.getProperty(metadataKey, "").trim() : override;
    }

    private record PackRequest(UUID id, String url, byte[] hash, String prompt, boolean required) {
        private PackRequest {
            hash = hash.clone();
        }

        @Override
        public byte[] hash() {
            return hash.clone();
        }
    }
}
