package hu.taliann.icesmp.classspec.application;

import hu.taliann.icesmp.classspec.domain.*;
import hu.taliann.icesmp.classspec.persistence.*;

import java.time.Duration;
import java.util.*;
import java.util.concurrent.*;

/** Greenfield initialization, quarantine, logout and disable regressions. */
public final class ClassProfileLifecycleRegressionSuite {
    private static final UUID PLAYER=UUID.fromString("00000000-0000-0000-0000-000000000701");
    private static int assertions;
    private ClassProfileLifecycleRegressionSuite(){}
    public static void main(String[] args){missingInitializesRevisionZero();repeatedJoinDoesNotResetRevision();parallelInitializationReloadsWinner();quarantineNeverCreatesEmptyProfile();corruptLoadFailureBlocksWithoutOverwrite();logoutFlushesBeforeInvalidation();disableWaitsForAdmittedJoinAndRejectsLateJoin();System.out.println("Class profile lifecycle regression suite passed. assertions="+assertions);}
    private static void missingInitializesRevisionZero(){FakeRepo r=new FakeRepo();var result=new ClassProfileLifecycleService(r).join(PLAYER).toCompletableFuture().join();check(result.status()==ClassProfileLifecycleService.Status.READY,"ready");check(result.initialized(),"initialized");check(result.profile().ownerId().equals(PLAYER),"owner");check(result.profile().revision()==0,"revision zero");check(r.lastExpected==-1,"missing revision contract");check(r.saves==1,"one save");}
    private static void repeatedJoinDoesNotResetRevision(){FakeRepo r=new FakeRepo();ClassProfileLifecycleService s=new ClassProfileLifecycleService(r);ClassProfile first=s.join(PLAYER).toCompletableFuture().join().profile();r.profile=first.toBuilder().revision(1).primaryClassId("wizard").classLevel(1).build();var second=s.join(PLAYER).toCompletableFuture().join();check(!second.initialized(),"not reinitialized");check(second.profile().revision()==1,"revision retained");check(r.saves==1,"no second init save");}
    private static void parallelInitializationReloadsWinner(){RaceRepo r=new RaceRepo();ClassProfileLifecycleService a=new ClassProfileLifecycleService(r),b=new ClassProfileLifecycleService(r);var fa=a.join(PLAYER).toCompletableFuture();var fb=b.join(PLAYER).toCompletableFuture();r.awaitSaveCalls(2);r.commitWinner();var ra=fa.join();var rb=fb.join();check(ra.status()==ClassProfileLifecycleService.Status.READY&&rb.status()==ClassProfileLifecycleService.Status.READY,"both ready");check(r.profile!=null&&r.profile.revision()==0,"one canonical revision zero");check(ra.profile().equals(rb.profile()),"loser reloads winner");check(r.committedSaves==1,"exactly one first commit");}
    private static void quarantineNeverCreatesEmptyProfile(){FakeRepo r=new FakeRepo();r.loadResult=ClassProfileRepository.LoadResult.quarantined("bad digest","ev-1");var result=new ClassProfileLifecycleService(r).join(PLAYER).toCompletableFuture().join();check(result.status()==ClassProfileLifecycleService.Status.QUARANTINED,"quarantined");check(result.evidenceId().equals("ev-1"),"evidence retained");check(r.saves==0,"no empty overwrite");}
    private static void corruptLoadFailureBlocksWithoutOverwrite(){FakeRepo r=new FakeRepo();r.loadFailure=new IllegalStateException("decode failed");var result=new ClassProfileLifecycleService(r).join(PLAYER).toCompletableFuture().join();check(result.status()==ClassProfileLifecycleService.Status.BLOCKED,"blocked");check(r.saves==0,"no write");check(r.blockReason.contains("decode failed"),"diagnostic");}
    private static void logoutFlushesBeforeInvalidation(){FakeRepo r=new FakeRepo();r.profile=ClassProfile.empty(PLAYER,0);new ClassProfileLifecycleService(r).logout(PLAYER).toCompletableFuture().join();check(r.events.equals(List.of("flush","invalidate")),"flush then invalidate");}
    private static void disableWaitsForAdmittedJoinAndRejectsLateJoin(){FakeRepo r=new FakeRepo();r.loadGate=new CompletableFuture<>();ClassProfileLifecycleService service=new ClassProfileLifecycleService(r);var join=service.join(PLAYER).toCompletableFuture();var disable=service.prepareDisable().toCompletableFuture();check(!disable.isDone(),"disable waits");var late=service.join(UUID.randomUUID()).toCompletableFuture().join();check(late.status()==ClassProfileLifecycleService.Status.BLOCKED,"late blocked");r.loadGate.complete(ClassProfileRepository.LoadResult.missing());join.join();disable.join();check(r.events.contains("flushAll"),"flush all after join");check(!service.accepting(),"admission stopped");}
    private static class FakeRepo implements ClassProfileRepository{volatile ClassProfile profile;volatile LoadResult loadResult;volatile RuntimeException loadFailure;volatile CompletableFuture<LoadResult> loadGate;volatile String blockReason="";long lastExpected=Long.MIN_VALUE;int saves;final List<String> events=new CopyOnWriteArrayList<>();public CompletionStage<LoadResult> load(UUID id){if(loadFailure!=null)return CompletableFuture.failedFuture(loadFailure);if(loadGate!=null)return loadGate;return CompletableFuture.completedFuture(loadResult!=null?loadResult:profile==null?LoadResult.missing():LoadResult.found(profile));}public CompletionStage<ClassProfile> save(UUID id,long expected,ClassProfile next){saves++;lastExpected=expected;if(profile!=null||expected!=MISSING_REVISION)return CompletableFuture.failedFuture(new ProfileRepositoryException.RevisionConflict(expected,profile==null?-1:profile.revision(),"conflict"));profile=next;return CompletableFuture.completedFuture(next);}public CompletionStage<QuarantineRecord> quarantine(UUID id,byte[] p,String reason){return CompletableFuture.completedFuture(new QuarantineRecord(id,1,reason,"ev","file"));}public CompletionStage<ClassProfile> recover(UUID id,String e,String a){return CompletableFuture.failedFuture(new UnsupportedOperationException());}public CompletionStage<Void> flush(UUID id){events.add("flush");return CompletableFuture.completedFuture(null);}public CompletionStage<Void> flushAll(){events.add("flushAll");return CompletableFuture.completedFuture(null);}public CompletionStage<ShutdownResult> shutdown(Duration t){return CompletableFuture.completedFuture(new ShutdownResult(true,0,""));}public void invalidate(UUID id){events.add("invalidate");}public Optional<ClassProfile> cached(UUID id){return Optional.ofNullable(profile);}public Optional<String> sessionBlockReason(UUID id){return blockReason.isBlank()?Optional.empty():Optional.of(blockReason);}public Optional<String> quarantineReason(UUID id){return Optional.empty();}public void blockSession(UUID id,String reason){blockReason=reason;}}
    private static final class RaceRepo extends FakeRepo{final List<CompletableFuture<ClassProfile>> pending=new CopyOnWriteArrayList<>();int saveCalls,committedSaves;@Override public CompletionStage<ClassProfile> save(UUID id,long expected,ClassProfile next){saveCalls++;CompletableFuture<ClassProfile> f=new CompletableFuture<>();pending.add(f);return f;}void awaitSaveCalls(int n){long d=System.nanoTime()+TimeUnit.SECONDS.toNanos(2);while(saveCalls<n&&System.nanoTime()<d)Thread.onSpinWait();check(saveCalls==n,"parallel saves admitted");}void commitWinner(){profile=ClassProfile.empty(PLAYER,0);committedSaves=1;pending.get(0).complete(profile);pending.get(1).completeExceptionally(new ProfileRepositoryException.RevisionConflict(-1,0,"concurrent initialization"));}}
    private static void check(boolean v,String m){assertions++;if(!v)throw new AssertionError(m);}
}
