package hu.taliann.icesmp.classspec.transaction;

import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;

/** Respec WAL round-trip, strict parsing and crash-decision regressions. */
public final class RespecTransactionRegressionSuite {
    private static int assertions;
    private RespecTransactionRegressionSuite(){}
    public static void main(String[] args)throws Exception{decisionTable();journalRoundTripAndRestart();journalStrictness();idempotentDelete();System.out.println("Respec transaction regression suite passed. assertions="+assertions);}
    private static void decisionTable(){using(true,10,RespecRecoveryProtocol.WalletWitness.DEBITED,RespecRecoveryProtocol.Action.COMMIT_WALLET_AND_COMPLETE);using(true,10,RespecRecoveryProtocol.WalletWitness.COMMITTED,RespecRecoveryProtocol.Action.COMPLETE);using(false,10,RespecRecoveryProtocol.WalletWitness.DEBITED,RespecRecoveryProtocol.Action.ROLLBACK_WALLET_AND_ABORT);using(false,10,RespecRecoveryProtocol.WalletWitness.MISSING,RespecRecoveryProtocol.Action.DELETE_INTENT_AND_ABORT);using(true,10,RespecRecoveryProtocol.WalletWitness.MISSING,RespecRecoveryProtocol.Action.BLOCK_INCONSISTENT);using(false,10,RespecRecoveryProtocol.WalletWitness.COMMITTED,RespecRecoveryProtocol.Action.BLOCK_INCONSISTENT);using(true,0,RespecRecoveryProtocol.WalletWitness.NOT_REQUIRED,RespecRecoveryProtocol.Action.COMPLETE);using(false,0,RespecRecoveryProtocol.WalletWitness.MISSING,RespecRecoveryProtocol.Action.DELETE_INTENT_AND_ABORT);expect(IllegalArgumentException.class,()->RespecRecoveryProtocol.decide(false,Double.NaN,RespecRecoveryProtocol.WalletWitness.MISSING));expect(IllegalArgumentException.class,()->RespecRecoveryProtocol.decide(false,-1,RespecRecoveryProtocol.WalletWitness.MISSING));}
    private static void journalRoundTripAndRestart()throws Exception{Path dir=Files.createTempDirectory("respec-wal-");try{UUID player=UUID.fromString("00000000-0000-0000-0000-000000000801");RespecTransactionJournal first=new RespecTransactionJournal(dir);var intent=new RespecTransactionJournal.Entry("respec-1",player,RespecTransactionJournal.Stage.INTENT,"gold",25.5,1_700_000_000_000L,7,false,false,Map.of(),Map.of(),"intent");first.save(intent);check(first.load("respec-1").equals(intent),"intent roundtrip");var debited=intent.withWallet(true,Map.of("gold",100.0),Map.of("gold",74.5));first.save(debited);RespecTransactionJournal restarted=new RespecTransactionJournal(dir);check(restarted.load("respec-1").equals(debited),"restart durable");check(restarted.findByPlayer(player).equals(List.of(debited)),"owner lookup");var committed=debited.withStage(RespecTransactionJournal.Stage.PROFILE_COMMITTED,"profile committed");restarted.save(committed);check(restarted.load("respec-1").stage()==RespecTransactionJournal.Stage.PROFILE_COMMITTED,"stage persisted");}finally{delete(dir);}}
    private static void journalStrictness()throws Exception{Path dir=Files.createTempDirectory("respec-strict-");try{RespecTransactionJournal j=new RespecTransactionJournal(dir);UUID p=UUID.randomUUID();expect(IllegalArgumentException.class,()->new RespecTransactionJournal.Entry("",p,RespecTransactionJournal.Stage.INTENT,"gold",1,1,0,false,false,Map.of(),Map.of(),""));expect(IllegalArgumentException.class,()->new RespecTransactionJournal.Entry("op",p,RespecTransactionJournal.Stage.INTENT,"gold",Double.POSITIVE_INFINITY,1,0,false,false,Map.of(),Map.of(),""));var e=new RespecTransactionJournal.Entry("strict-op",p,RespecTransactionJournal.Stage.INTENT,"gold",1,2,0,false,false,Map.of(),Map.of(),"");j.save(e);Path file=Files.list(dir).findFirst().orElseThrow();String raw=Files.readString(file,StandardCharsets.ISO_8859_1);Files.writeString(file,raw+"unknown-field=x\n",StandardCharsets.ISO_8859_1);expect(RespecTransactionJournal.JournalException.class,()->j.load("strict-op"));}finally{delete(dir);}}
    private static void idempotentDelete()throws Exception{Path dir=Files.createTempDirectory("respec-delete-");try{RespecTransactionJournal j=new RespecTransactionJournal(dir);UUID p=UUID.randomUUID();j.save(new RespecTransactionJournal.Entry("delete-op",p,RespecTransactionJournal.Stage.INTENT,"gold",0,2,0,false,false,Map.of(),Map.of(),""));j.delete("delete-op");j.delete("delete-op");check(j.load("delete-op")==null,"delete idempotent");}finally{delete(dir);}}
    private static void using(boolean p,double a,RespecRecoveryProtocol.WalletWitness w,RespecRecoveryProtocol.Action expected){check(RespecRecoveryProtocol.decide(p,a,w).action()==expected,p+"/"+w);}private static void check(boolean v,String m){assertions++;if(!v)throw new AssertionError(m);}private static void expect(Class<? extends Throwable> t,Runnable r){assertions++;try{r.run();throw new AssertionError("Expected "+t.getSimpleName());}catch(Throwable x){if(!t.isInstance(x))throw new AssertionError("Expected "+t.getSimpleName()+" got "+x,x);}}private static void delete(Path root)throws Exception{if(Files.notExists(root))return;try(var s=Files.walk(root)){s.sorted(Comparator.reverseOrder()).forEach(p->{try{Files.deleteIfExists(p);}catch(Exception e){throw new RuntimeException(e);}});}}
}
