package hu.taliann.icesmp.playerprofile.persistence;

import hu.taliann.icesmp.classspec.domain.*;
import hu.taliann.icesmp.playerprofile.domain.*;
import hu.taliann.icesmp.playerprofile.domain.section.*;
import java.time.Instant;
import java.util.*;

/** Strict structured YAML mapping. It never accepts Java object tags or opaque binary profile blobs. */
public final class StructuredPlayerProfileYaml {
    public static final String SECTION_FORMAT="ICESMP-PLAYER-PROFILE-SECTION";
    private StructuredPlayerProfileYaml(){}

    public static Map<String,Object> encodeManifest(PlayerProfileManifest manifest){
        LinkedHashMap<String,Object> root=new LinkedHashMap<>();
        root.put("format",manifest.format());root.put("schema",manifest.schema());root.put("player-id",manifest.playerId().toString());
        root.put("profile-revision",manifest.profileRevision());root.put("created-at",manifest.createdAt().toEpochMilli());root.put("updated-at",manifest.updatedAt().toEpochMilli());root.put("lifecycle-status",manifest.lifecycleStatus());
        LinkedHashMap<String,Object> sections=new LinkedHashMap<>();manifest.sections().entrySet().stream().sorted(Map.Entry.comparingByKey()).forEach(e->{LinkedHashMap<String,Object> r=new LinkedHashMap<>();r.put("schema",e.getValue().schema());r.put("revision",e.getValue().revision());sections.put(e.getKey().id(),r);});root.put("sections",sections);if(!manifest.recoveryMetadata().isEmpty())root.put("recovery",new TreeMap<>(manifest.recoveryMetadata()));return root;
    }
    public static PlayerProfileManifest decodeManifest(UUID expected,Map<String,Object> root){
        requireKeys(root,Set.of("format","schema","player-id","profile-revision","created-at","updated-at","lifecycle-status","sections","recovery"),Set.of("format","schema","player-id","profile-revision","created-at","updated-at","sections"));
        UUID id=uuid(root.get("player-id"),"player-id");if(!id.equals(expected))throw new IllegalArgumentException("manifest owner mismatch");
        EnumMap<ProfileSectionId,SectionRevision> sections=new EnumMap<>(ProfileSectionId.class);Map<String,Object> raw=map(root.get("sections"),"sections");for(var e:raw.entrySet()){ProfileSectionId sid=ProfileSectionId.parse(e.getKey());Map<String,Object> r=map(e.getValue(),"section revision");requireKeys(r,Set.of("schema","revision"),Set.of("schema","revision"));if(sections.put(sid,new SectionRevision(integer(r.get("schema"),"schema"),number(r.get("revision"),"revision")))!=null)throw new IllegalArgumentException("duplicate manifest section");}
        return new PlayerProfileManifest(id,string(root.get("format"),"format"),integer(root.get("schema"),"schema"),number(root.get("profile-revision"),"profile-revision"),Instant.ofEpochMilli(number(root.get("created-at"),"created-at")),Instant.ofEpochMilli(number(root.get("updated-at"),"updated-at")),sections,optionalString(root.get("lifecycle-status"),"active"),stringMap(root.get("recovery"),"recovery"));
    }

    public static Map<String,Object> encodeSection(ProfileSectionSnapshot<?> snapshot){
        LinkedHashMap<String,Object> root=new LinkedHashMap<>();root.put("format",SECTION_FORMAT);root.put("section",snapshot.sectionId().id());root.put("schema",snapshot.schema());root.put("revision",snapshot.revision());root.put("updated-at",snapshot.updatedAt().toEpochMilli());root.put("health",healthMap(snapshot.health()));root.put("data",encodeData(snapshot.value()));if(!snapshot.extensions().isEmpty())root.put("extensions",snapshot.extensions());return normalizeRoot(root);
    }
    public static ProfileSectionSnapshot<?> decodeSection(ProfileSectionId expected,Map<String,Object> root){
        requireKeys(root,Set.of("format","section","schema","revision","updated-at","health","data","extensions"),Set.of("format","section","schema","revision","updated-at","data"));
        if(!SECTION_FORMAT.equals(string(root.get("format"),"format")))throw new IllegalArgumentException("unsupported section format");ProfileSectionId actual=ProfileSectionId.parse(string(root.get("section"),"section"));if(actual!=expected)throw new IllegalArgumentException("section mismatch");int schema=integer(root.get("schema"),"schema");if(schema>expected.currentSchema())throw new IllegalArgumentException("future mandatory section schema");long revision=number(root.get("revision"),"revision");Instant updated=Instant.ofEpochMilli(number(root.get("updated-at"),"updated-at"));SectionHealth health=decodeHealth(root.get("health"));ProfileSectionData data=decodeData(expected,map(root.get("data"),"data"));return new ProfileSectionSnapshot<>(expected,schema,revision,updated,data,health,objectMap(root.get("extensions"),"extensions"));
    }

    private static Map<String,Object> healthMap(SectionHealth h){LinkedHashMap<String,Object> m=new LinkedHashMap<>();m.put("status",h.status().name().toLowerCase(Locale.ROOT));if(!h.diagnostic().isEmpty())m.put("diagnostic",h.diagnostic());if(!h.evidenceId().isEmpty())m.put("evidence-id",h.evidenceId());if(!h.recoveryAuditId().isEmpty())m.put("recovery-audit-id",h.recoveryAuditId());return m;}
    private static SectionHealth decodeHealth(Object raw){if(raw==null)return SectionHealth.healthy();Map<String,Object> m=map(raw,"health");requireKeys(m,Set.of("status","diagnostic","evidence-id","recovery-audit-id"),Set.of("status"));SectionHealth.Status s=enumValue(SectionHealth.Status.class,string(m.get("status"),"status"));return new SectionHealth(s,optionalString(m.get("diagnostic"),""),optionalString(m.get("evidence-id"),""),optionalString(m.get("recovery-audit-id"),""));}

    private static Map<String,Object> encodeData(ProfileSectionData d){
        LinkedHashMap<String,Object> m=new LinkedHashMap<>();
        if(d instanceof IdentitySection s){m.put("last-known-name",s.lastKnownName());m.put("first-seen-at",s.firstSeenAt());m.put("last-seen-at",s.lastSeenAt());m.put("last-successful-load-at",s.lastSuccessfulLoadAt());m.put("public-visible",s.publicVisible());m.put("api-visible",s.apiVisible());m.put("account-links",s.accountLinks());m.put("extensions",s.extensions());}
        else if(d instanceof LifecycleSection s){m.put("status",s.status());m.put("profile-created-at",s.profileCreatedAt());m.put("updated-at",s.updatedAt());m.put("last-join-at",s.lastJoinAt());m.put("last-quit-at",s.lastQuitAt());m.put("session-generation",s.sessionGeneration());m.put("extensions",s.extensions());}
        else if(d instanceof OnboardingSection s){m.put("steps",s.steps());m.put("claimed-rewards",s.claimedRewards());m.put("codex-entries",s.codexEntries());m.put("memory-spec-unlocked",s.memorySpecUnlocked());m.put("extensions",s.extensions());}
        else if(d instanceof FactionSection s){m.put("membership-id",s.membershipId());m.put("last-chosen-faction",s.lastChosenFaction());m.put("ever-chosen",s.everChosen());m.put("joined-at",s.joinedAt());m.put("left-at",s.leftAt());m.put("history",s.history());m.put("reputation",s.reputation());m.put("cooldowns",s.cooldowns());m.put("extensions",s.extensions());}
        else if(d instanceof EconomySection s){m.put("wallets",s.wallets());m.put("bank-balance",s.bankBalance());m.put("debts",s.debts());m.put("pending-rewards",s.pendingRewards());m.put("operation-receipts",s.operationReceipts());m.put("extensions",s.extensions());}
        else if(d instanceof ClassSpecSection s)return encodeClassSpec(s);
        else if(d instanceof ProfessionSection s){m.put("experience",s.experience());m.put("levels",s.levels());m.put("specializations",s.specializations());m.put("recipes",s.recipes());m.put("weekly-progress",s.weeklyProgress());m.put("extensions",s.extensions());}
        else if(d instanceof SpellbookSection s){m.put("provenance",s.provenance());m.put("selected-spell",s.selectedSpell());m.put("favorites",s.favorites());m.put("mastery",s.mastery());m.put("persistent-cooldowns",s.persistentCooldowns());m.put("ui-state",s.uiState());m.put("extensions",s.extensions());}
        else if(d instanceof TalentSection s){m.put("points",s.points());m.put("bonus-points",s.bonusPoints());m.put("purchased",s.purchased());m.put("provenance",s.provenance());m.put("loadout",s.loadout());m.put("refund-receipts",s.refundReceipts());m.put("extensions",s.extensions());}
        else if(d instanceof QuestSection s){m.put("active",s.active());m.put("completed",s.completed());m.put("reward-receipts",s.rewardReceipts());m.put("cooldowns",s.cooldowns());m.put("community-contributions",s.communityContributions());m.put("claimable-rewards",s.claimableRewards());m.put("extensions",s.extensions());}
        else if(d instanceof CompanionSection s){m.put("roster",s.roster());m.put("active-companion-id",s.activeCompanionId());m.put("extensions",s.extensions());}
        else if(d instanceof RelicSection s){m.put("owned",s.owned());m.put("claimed-milestones",s.claimedMilestones());m.put("extensions",s.extensions());}
        else if(d instanceof AchievementSection s){m.put("unlocked",s.unlocked());m.put("public-achievements",s.publicAchievements());m.put("claimed-rewards",s.claimedRewards());m.put("bestiary",s.bestiary());m.put("extensions",s.extensions());}
        else if(d instanceof StatisticsSection s){m.put("lifetime",s.lifetime());m.put("season",s.season());m.put("claimed-milestones",s.claimedMilestones());m.put("extensions",s.extensions());}
        else if(d instanceof PreferenceSection s){m.put("language",s.language());m.put("hud-enabled",s.hudEnabled());m.put("scoreboard-enabled",s.scoreboardEnabled());m.put("notifications-enabled",s.notificationsEnabled());m.put("public-profile",s.publicProfile());m.put("public-companion",s.publicCompanion());m.put("public-achievements",s.publicAchievements());m.put("public-class-faction-spec",s.publicClassFactionSpec());m.put("api-visible",s.apiVisible());m.put("values",s.values());m.put("extensions",s.extensions());}
        else if(d instanceof SocialLinkSection s){m.put("links",s.links());m.put("extensions",s.extensions());}
        else if(d instanceof ModerationSection s){m.put("active-punishment-refs",s.activePunishmentRefs());m.put("strike-count",s.strikeCount());m.put("admin-note-refs",s.adminNoteRefs());m.put("audit-state",s.auditState());m.put("extensions",s.extensions());}
        else if(d instanceof OperationSection s){LinkedHashMap<String,Object> ops=new LinkedHashMap<>();s.operations().forEach((k,v)->ops.put(k,operationMap(v)));m.put("operations",ops);m.put("extensions",s.extensions());}
        else throw new IllegalArgumentException("unsupported section type");return m;
    }

    private static ProfileSectionData decodeData(ProfileSectionId id,Map<String,Object> m){long now=0L;return switch(id){
        case IDENTITY -> new IdentitySection(opt(m,"last-known-name"),nonNegative(m,"first-seen-at",0),nonNegative(m,"last-seen-at",0),nonNegative(m,"last-successful-load-at",0),bool(m,"public-visible",true),bool(m,"api-visible",false),stringMap(m.get("account-links"),"account-links"),objectMap(m.get("extensions"),"extensions"));
        case LIFECYCLE -> new LifecycleSection(optionalString(m.get("status"),"active"),nonNegative(m,"profile-created-at",now),nonNegative(m,"updated-at",now),nonNegative(m,"last-join-at",0),nonNegative(m,"last-quit-at",0),nonNegative(m,"session-generation",0),objectMap(m.get("extensions"),"extensions"));
        case ONBOARDING -> new OnboardingSection(stringMap(m.get("steps"),"steps"),stringSet(m.get("claimed-rewards"),"claimed-rewards"),stringSet(m.get("codex-entries"),"codex-entries"),bool(m,"memory-spec-unlocked",false),objectMap(m.get("extensions"),"extensions"));
        case FACTION -> new FactionSection(opt(m,"membership-id"),opt(m,"last-chosen-faction"),bool(m,"ever-chosen",false),nonNegative(m,"joined-at",0),nonNegative(m,"left-at",0),stringList(m.get("history"),"history"),longMap(m.get("reputation"),"reputation"),longMap(m.get("cooldowns"),"cooldowns"),objectMap(m.get("extensions"),"extensions"));
        case ECONOMY -> new EconomySection(longMap(m.get("wallets"),"wallets"),nonNegative(m,"bank-balance",0),longMap(m.get("debts"),"debts"),stringMap(m.get("pending-rewards"),"pending-rewards"),stringSet(m.get("operation-receipts"),"operation-receipts"),objectMap(m.get("extensions"),"extensions"));
        case CLASS_SPEC -> decodeClassSpec(m);
        case PROFESSIONS -> new ProfessionSection(longMap(m.get("experience"),"experience"),intMap(m.get("levels"),"levels"),stringMap(m.get("specializations"),"specializations"),stringSet(m.get("recipes"),"recipes"),longMap(m.get("weekly-progress"),"weekly-progress"),objectMap(m.get("extensions"),"extensions"));
        case SPELLBOOK -> new SpellbookSection(setMap(m.get("provenance"),"provenance"),opt(m,"selected-spell"),stringList(m.get("favorites"),"favorites"),longMap(m.get("mastery"),"mastery"),longMap(m.get("persistent-cooldowns"),"persistent-cooldowns"),stringMap(m.get("ui-state"),"ui-state"),objectMap(m.get("extensions"),"extensions"));
        case TALENTS -> new TalentSection(integerDefault(m,"points",0),integerDefault(m,"bonus-points",0),stringSet(m.get("purchased"),"purchased"),setMap(m.get("provenance"),"provenance"),stringMap(m.get("loadout"),"loadout"),stringSet(m.get("refund-receipts"),"refund-receipts"),objectMap(m.get("extensions"),"extensions"));
        case QUESTS -> new QuestSection(nestedLongMap(m.get("active"),"active"),stringSet(m.get("completed"),"completed"),stringSet(m.get("reward-receipts"),"reward-receipts"),longMap(m.get("cooldowns"),"cooldowns"),longMap(m.get("community-contributions"),"community-contributions"),stringSet(m.get("claimable-rewards"),"claimable-rewards"),objectMap(m.get("extensions"),"extensions"));
        case COMPANIONS -> new CompanionSection(nestedObjectMap(m.get("roster"),"roster"),opt(m,"active-companion-id"),objectMap(m.get("extensions"),"extensions"));
        case RELICS -> new RelicSection(nestedStringMap(m.get("owned"),"owned"),stringSet(m.get("claimed-milestones"),"claimed-milestones"),objectMap(m.get("extensions"),"extensions"));
        case ACHIEVEMENTS -> new AchievementSection(stringSet(m.get("unlocked"),"unlocked"),stringSet(m.get("public-achievements"),"public-achievements"),stringSet(m.get("claimed-rewards"),"claimed-rewards"),longMap(m.get("bestiary"),"bestiary"),objectMap(m.get("extensions"),"extensions"));
        case STATISTICS -> new StatisticsSection(longMap(m.get("lifetime"),"lifetime"),longMap(m.get("season"),"season"),stringSet(m.get("claimed-milestones"),"claimed-milestones"),objectMap(m.get("extensions"),"extensions"));
        case PREFERENCES -> new PreferenceSection(optionalString(m.get("language"),"hu_HU"),bool(m,"hud-enabled",true),bool(m,"scoreboard-enabled",true),bool(m,"notifications-enabled",true),bool(m,"public-profile",true),bool(m,"public-companion",true),bool(m,"public-achievements",true),bool(m,"public-class-faction-spec",true),bool(m,"api-visible",false),stringMap(m.get("values"),"values"),objectMap(m.get("extensions"),"extensions"));
        case SOCIAL_LINKS -> new SocialLinkSection(stringMap(m.get("links"),"links"),objectMap(m.get("extensions"),"extensions"));
        case MODERATION -> new ModerationSection(stringSet(m.get("active-punishment-refs"),"active-punishment-refs"),integerDefault(m,"strike-count",0),stringSet(m.get("admin-note-refs"),"admin-note-refs"),stringMap(m.get("audit-state"),"audit-state"),objectMap(m.get("extensions"),"extensions"));
        case OPERATIONS -> new OperationSection(operationMapValues(m.get("operations")),objectMap(m.get("extensions"),"extensions"));
    };}

    private static Map<String,Object> encodeClassSpec(ClassSpecSection s){LinkedHashMap<String,Object> m=new LinkedHashMap<>();m.put("schema-version",s.schemaVersion());m.put("revision",s.revision());m.put("status",s.status().name().toLowerCase(Locale.ROOT));m.put("primary-class-id",s.primaryClassId());m.put("class-level",s.classLevel());m.put("class-experience",s.classExperience());m.put("active-slot",s.activeSlot()==null?"":s.activeSlot().name().toLowerCase(Locale.ROOT));m.put("second-spec-unlocked",s.secondSpecUnlocked());List<Object> loadouts=new ArrayList<>();for(LoadoutSlot slot:LoadoutSlot.values())loadouts.add(loadoutMap(slot,s.loadout(slot)));m.put("loadouts",loadouts);LinkedHashMap<String,Object> ops=new LinkedHashMap<>();s.operations().forEach((k,v)->ops.put(k,classOperationMap(v)));m.put("operations",ops);m.put("diagnostics",diagnosticsMap(s.diagnostics()));return m;}
    private static ClassSpecSection decodeClassSpec(Map<String,Object> m){ClassSpecSection.Builder b=ClassSpecSection.builder().schemaVersion(integerDefault(m,"schema-version",ClassSpecSection.SCHEMA_VERSION)).revision(nonNegative(m,"revision",0)).status(enumValue(ProfileStatus.class,optionalString(m.get("status"),"ready"))).primaryClassId(opt(m,"primary-class-id")).classLevel(integerDefault(m,"class-level",0)).classExperience(integerDefault(m,"class-experience",0)).secondSpecUnlocked(bool(m,"second-spec-unlocked",false)).diagnostics(decodeDiagnostics(m.get("diagnostics")));String active=opt(m,"active-slot");if(!active.isBlank())b.activeSlot(enumValue(LoadoutSlot.class,active));List<Object> loads=list(m.get("loadouts"),"loadouts");if(loads.size()!=2)throw new IllegalArgumentException("class-spec requires two loadouts");for(Object o:loads){Map<String,Object> lm=map(o,"loadout");LoadoutSlot slot=enumValue(LoadoutSlot.class,string(lm.get("slot"),"slot"));b.loadout(slot,decodeLoadout(lm));}Map<String,Object> ops=objectMap(m.get("operations"),"operations");for(var e:ops.entrySet())b.operation(decodeClassOperation(e.getKey(),map(e.getValue(),"operation")));return b.build();}
    private static Map<String,Object> loadoutMap(LoadoutSlot slot,ClassLoadout l){LinkedHashMap<String,Object> m=new LinkedHashMap<>();m.put("slot",slot.name().toLowerCase(Locale.ROOT));m.put("specialization-id",l.specializationId());m.put("status",l.status().name().toLowerCase(Locale.ROOT));if(l.sealReason()!=null)m.put("seal",sealMap(l.sealReason()));m.put("doctrine",l.doctrineChoices());m.put("mastery",Map.of("rank",l.mastery().rank(),"experience",l.mastery().experience()));if(l.soulbond()!=null)m.put("soulbond",soulbondMap(l.soulbond()));m.put("favorite-spells",l.favoriteSpells());m.put("selected-spell",l.selectedSpell());m.put("capstone",l.capstoneStatus().name().toLowerCase(Locale.ROOT));List<Object> roster=new ArrayList<>();l.companionRoster().values().stream().sorted(Comparator.comparing(c->c.companionId().toString())).forEach(c->roster.add(companionMap(c)));m.put("companions",roster);m.put("mechanics",l.mechanicState());m.put("diagnostic-note",l.diagnosticNote());return m;}
    private static ClassLoadout decodeLoadout(Map<String,Object> m){LoadoutStatus status=enumValue(LoadoutStatus.class,optionalString(m.get("status"),"empty"));String spec=opt(m,"specialization-id");SealReason seal=m.get("seal")==null?null:decodeSeal(map(m.get("seal"),"seal"));Map<String,Object> mastery=mapDefault(m.get("mastery"));MasteryProgress progress=new MasteryProgress(integerDefault(mastery,"rank",0),nonNegative(mastery,"experience",0));SoulbondState soul=m.get("soulbond")==null?null:decodeSoulbond(map(m.get("soulbond"),"soulbond"));Map<UUID,CompanionProfile> roster=new LinkedHashMap<>();for(Object raw:listDefault(m.get("companions"))){CompanionProfile c=decodeCompanion(map(raw,"companion"));if(roster.put(c.companionId(),c)!=null)throw new IllegalArgumentException("duplicate companion");}return new ClassLoadout(spec,status,seal,stringMap(m.get("doctrine"),"doctrine"),progress,soul,stringSet(m.get("favorite-spells"),"favorite-spells"),opt(m,"selected-spell"),enumValue(CapstoneStatus.class,optionalString(m.get("capstone"),"locked")),roster,stringMap(m.get("mechanics"),"mechanics"),opt(m,"diagnostic-note"));}
    private static Map<String,Object> sealMap(SealReason s){LinkedHashMap<String,Object> causes=new LinkedHashMap<>();s.gateIds().entrySet().stream().sorted(Map.Entry.comparingByKey()).forEach(e->causes.put(e.getKey().name().toLowerCase(Locale.ROOT),e.getValue()));return Map.of("causes",causes,"detail",s.detail());}
    private static SealReason decodeSeal(Map<String,Object> m){EnumMap<SealCause,String> causes=new EnumMap<>(SealCause.class);stringMap(m.get("causes"),"causes").forEach((k,v)->causes.put(enumValue(SealCause.class,k),v));return new SealReason(causes,opt(m,"detail"));}
    private static Map<String,Object> soulbondMap(SoulbondState s){return Map.of("signature-id",s.signatureId().toString(),"evolution",s.evolution(),"modules",s.modules(),"revision",s.revision(),"recovery-note",s.recoveryNote());}
    private static SoulbondState decodeSoulbond(Map<String,Object> m){return new SoulbondState(uuid(m.get("signature-id"),"signature-id"),integerDefault(m,"evolution",0),stringList(m.get("modules"),"modules"),nonNegative(m,"revision",0),opt(m,"recovery-note"));}
    private static Map<String,Object> companionMap(CompanionProfile c){LinkedHashMap<String,Object> m=new LinkedHashMap<>();m.put("id",c.companionId().toString());m.put("namespace",c.namespace());m.put("type",c.typeId());m.put("name",c.name());m.put("level",c.level());m.put("experience",c.experience());m.put("trait",c.traitId());m.put("stance",c.stance());m.put("equipment",c.equipmentIds());m.put("resummon-at",c.resummonAtEpochMillis());m.put("state",c.persistentState());return m;}
    private static CompanionProfile decodeCompanion(Map<String,Object> m){return new CompanionProfile(uuid(m.get("id"),"companion id"),string(m.get("namespace"),"namespace"),string(m.get("type"),"type"),opt(m,"name"),integerDefault(m,"level",1),nonNegative(m,"experience",0),opt(m,"trait"),opt(m,"stance"),stringList(m.get("equipment"),"equipment"),nonNegative(m,"resummon-at",0),stringMap(m.get("state"),"state"));}
    private static Map<String,Object> classOperationMap(ProfileOperation o){return Map.of("type",o.type().name().toLowerCase(Locale.ROOT),"status",o.status().name().toLowerCase(Locale.ROOT),"target",o.target(),"amount",o.amount(),"currency-id",o.currencyId(),"started-revision",o.startedRevision(),"detail",o.detail());}
    private static ProfileOperation decodeClassOperation(String id,Map<String,Object> m){return new ProfileOperation(id,enumValue(ProfileOperationType.class,string(m.get("type"),"type")),enumValue(ProfileOperationStatus.class,string(m.get("status"),"status")),opt(m,"target"),optionalString(m.get("amount"),"0"),opt(m,"currency-id"),nonNegative(m,"started-revision",0),opt(m,"detail"));}
    private static Map<String,Object> diagnosticsMap(ProfileDiagnostics d){return Map.of("quarantine-evidence-id",d.quarantineEvidenceId(),"quarantine-reason",d.quarantineReason(),"recovery-audit-id",d.recoveryAuditId(),"session-block-reason",d.sessionBlockReason());}
    private static ProfileDiagnostics decodeDiagnostics(Object raw){Map<String,Object> m=mapDefault(raw);return new ProfileDiagnostics(opt(m,"quarantine-evidence-id"),opt(m,"quarantine-reason"),opt(m,"recovery-audit-id"),opt(m,"session-block-reason"));}
    private static Map<String,Object> operationMap(PlayerProfileOperation o){return Map.of("type",o.type(),"status",o.status().name().toLowerCase(Locale.ROOT),"fingerprint",o.fingerprint(),"created-at",o.createdAt().toEpochMilli(),"updated-at",o.updatedAt().toEpochMilli(),"metadata",o.metadata());}
    private static Map<String,PlayerProfileOperation> operationMapValues(Object raw){Map<String,Object> m=objectMap(raw,"operations");LinkedHashMap<String,PlayerProfileOperation> out=new LinkedHashMap<>();for(var e:m.entrySet()){Map<String,Object> v=map(e.getValue(),"operation");out.put(e.getKey(),new PlayerProfileOperation(e.getKey(),string(v.get("type"),"type"),enumValue(PlayerProfileOperation.Status.class,string(v.get("status"),"status")),string(v.get("fingerprint"),"fingerprint"),Instant.ofEpochMilli(number(v.get("created-at"),"created-at")),Instant.ofEpochMilli(number(v.get("updated-at"),"updated-at")),stringMap(v.get("metadata"),"metadata")));}return out;}

    public static Object normalizeYamlValue(Object value){if(value==null||value instanceof String||value instanceof Boolean||value instanceof Number)return value;if(value instanceof org.bukkit.configuration.ConfigurationSection s)return normalizeYamlValue(s.getValues(false));if(value instanceof Map<?,?> m){LinkedHashMap<String,Object> out=new LinkedHashMap<>();for(var e:m.entrySet())out.put(String.valueOf(e.getKey()),normalizeYamlValue(e.getValue()));return out;}if(value instanceof Set<?> s){ArrayList<Object> ordered=new ArrayList<>(s);ordered.sort(Comparator.comparing(String::valueOf));ArrayList<Object> out=new ArrayList<>();for(Object o:ordered)out.add(normalizeYamlValue(o));return out;}if(value instanceof Collection<?> c){ArrayList<Object> out=new ArrayList<>();for(Object o:c)out.add(normalizeYamlValue(o));return out;}throw new IllegalArgumentException("unsupported YAML type: "+value.getClass().getName());}
    @SuppressWarnings("unchecked") public static Map<String,Object> normalizeRoot(Map<String,?> values){return (Map<String,Object>)normalizeYamlValue(values);}

    private static void requireKeys(Map<String,Object> m,Set<String> allowed,Set<String> required){for(String k:m.keySet())if(!allowed.contains(k))throw new IllegalArgumentException("unknown mandatory field: "+k);for(String k:required)if(!m.containsKey(k))throw new IllegalArgumentException("missing required field: "+k);}
    private static String opt(Map<String,Object> m,String k){return optionalString(m.get(k),"");}
    private static String optionalString(Object v,String d){return v==null?d:string(v,"string");}
    private static String string(Object v,String n){if(!(v instanceof String s))throw new IllegalArgumentException(n+" must be a string");return s;}
    private static boolean bool(Map<String,Object> m,String k,boolean d){Object v=m.get(k);if(v==null)return d;if(!(v instanceof Boolean b))throw new IllegalArgumentException(k+" must be boolean");return b;}
    private static int integerDefault(Map<String,Object> m,String k,int d){Object v=m.get(k);return v==null?d:integer(v,k);}
    private static int integer(Object v,String n){long x=number(v,n);if(x<Integer.MIN_VALUE||x>Integer.MAX_VALUE)throw new IllegalArgumentException(n+" outside int range");return (int)x;}
    private static long nonNegative(Map<String,Object> m,String k,long d){Object v=m.get(k);long x=v==null?d:number(v,k);if(x<0)throw new IllegalArgumentException(k+" must be non-negative");return x;}
    private static long number(Object v,String n){if(!(v instanceof Number x))throw new IllegalArgumentException(n+" must be numeric");if(v instanceof Double d&&(d.isNaN()||d.isInfinite()||d!=Math.rint(d)))throw new IllegalArgumentException(n+" must be an integer");return x.longValue();}
    private static UUID uuid(Object v,String n){try{return UUID.fromString(string(v,n));}catch(IllegalArgumentException e){throw new IllegalArgumentException(n+" must be UUID",e);}}
    private static <E extends Enum<E>> E enumValue(Class<E> type,String raw){try{return Enum.valueOf(type,raw.trim().toUpperCase(Locale.ROOT).replace('-','_'));}catch(Exception e){throw new IllegalArgumentException("invalid "+type.getSimpleName()+": "+raw,e);}}
    @SuppressWarnings("unchecked") private static Map<String,Object> map(Object v,String n){if(!(v instanceof Map<?,?> m))throw new IllegalArgumentException(n+" must be a map");LinkedHashMap<String,Object> out=new LinkedHashMap<>();for(var e:m.entrySet()){if(!(e.getKey() instanceof String k))throw new IllegalArgumentException(n+" key must be string");if(out.put(k,e.getValue())!=null)throw new IllegalArgumentException("duplicate key "+k);}return out;}
    private static Map<String,Object> mapDefault(Object v){return v==null?Map.of():map(v,"map");}
    private static List<Object> list(Object v,String n){if(!(v instanceof List<?> l))throw new IllegalArgumentException(n+" must be list");return List.copyOf(l);}
    private static List<Object> listDefault(Object v){return v==null?List.of():list(v,"list");}
    private static List<String> stringList(Object v,String n){if(v==null)return List.of();List<Object> l=list(v,n);ArrayList<String> out=new ArrayList<>();for(Object o:l)out.add(string(o,n));return List.copyOf(out);}
    private static Set<String> stringSet(Object v,String n){return Collections.unmodifiableSet(new LinkedHashSet<>(stringList(v,n)));}
    private static Map<String,String> stringMap(Object v,String n){if(v==null)return Map.of();Map<String,Object> m=map(v,n);LinkedHashMap<String,String> out=new LinkedHashMap<>();m.forEach((k,x)->out.put(k,string(x,n)));return Collections.unmodifiableMap(out);}
    private static Map<String,Long> longMap(Object v,String n){if(v==null)return Map.of();Map<String,Object> m=map(v,n);LinkedHashMap<String,Long> out=new LinkedHashMap<>();m.forEach((k,x)->{long q=number(x,n);if(q<0)throw new IllegalArgumentException(n+" must be non-negative");out.put(k,q);});return Collections.unmodifiableMap(out);}
    private static Map<String,Integer> intMap(Object v,String n){if(v==null)return Map.of();Map<String,Object> m=map(v,n);LinkedHashMap<String,Integer> out=new LinkedHashMap<>();m.forEach((k,x)->out.put(k,integer(x,n)));return Collections.unmodifiableMap(out);}
    private static Map<String,Set<String>> setMap(Object v,String n){if(v==null)return Map.of();Map<String,Object> m=map(v,n);LinkedHashMap<String,Set<String>> out=new LinkedHashMap<>();m.forEach((k,x)->out.put(k,stringSet(x,n)));return Collections.unmodifiableMap(out);}
    private static Map<String,Map<String,Long>> nestedLongMap(Object v,String n){if(v==null)return Map.of();Map<String,Object> m=map(v,n);LinkedHashMap<String,Map<String,Long>> out=new LinkedHashMap<>();m.forEach((k,x)->out.put(k,longMap(x,n)));return Collections.unmodifiableMap(out);}
    private static Map<String,Map<String,String>> nestedStringMap(Object v,String n){if(v==null)return Map.of();Map<String,Object> m=map(v,n);LinkedHashMap<String,Map<String,String>> out=new LinkedHashMap<>();m.forEach((k,x)->out.put(k,stringMap(x,n)));return Collections.unmodifiableMap(out);}
    private static Map<String,Map<String,Object>> nestedObjectMap(Object v,String n){if(v==null)return Map.of();Map<String,Object> m=map(v,n);LinkedHashMap<String,Map<String,Object>> out=new LinkedHashMap<>();m.forEach((k,x)->out.put(k,objectMap(x,n)));return Collections.unmodifiableMap(out);}
    private static Map<String,Object> objectMap(Object v,String n){if(v==null)return Map.of();return ImmutableValues.map(map(v,n));}
}