#!/usr/bin/env python3
"""Generate the repetitive BetterHud 1.14.1 layout from the generic IceSMP HUD contract."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LAYOUT_DIR = ROOT / "deploy" / "betterhud" / "layouts"

FACTION_THEMES = {"guest": "ice", "red": "ember", "blue": "frost", "neutral": "guild", "dark": "lich"}
CLASSES = ("warrior", "evoker", "archer", "shaman", "monk", "paladin", "demon_hunter",
           "druid", "priest", "death_knight", "assassin", "warlock", "wizard")


def condition(name, placeholder, value, operation="==", indent=6):
    pad = " " * indent
    return [f"{pad}{name}:", f'{pad}  first: "string:{placeholder}"',
            f'{pad}  second: "\'{value}\'"', f'{pad}  operation: "{operation}"']


def image(lines, key, name, x, y, layer, conditions=(), color_overrides=(), scale=None):
    lines += [f"    {key}:", f"      name: {name}", f"      x: {x}", f"      y: {y}", f"      layer: {layer}"]
    if scale is not None:
        lines.append(f"      scale: {scale}")
    if color_overrides:
        lines.append("      color-overrides:")
        for override, color, placeholder, value in color_overrides:
            lines += [f"        {override}:", f'          color: "{color}"',
                      f'          first: "string:{placeholder}"', f'          second: "\'{value}\'"',
                      '          operation: "=="']
    if conditions:
        lines.append("      conditions:")
        for args in conditions:
            lines += condition(*args, indent=8)


def text(lines, index, pattern, x, y, scale, conditions=()):
    lines += [f"    {index}:", "      name: icesmp_class_font", f'      pattern: "{pattern}"',
              f"      x: {x}", f"      y: {y}", f"      scale: {scale}", "      align: left",
              "      layer: 4", "      outline: true", "      use-legacy-format: false"]
    if conditions:
        lines.append("      conditions:")
        for args in conditions:
            lines += condition(*args, indent=8)


def main():
    identity = [
        "# GENERATED by scripts/generate_betterhud_layout.py; edit the generator, not this file.",
        "# Persistent identity and faction skin; consumes only immutable IceSMP snapshot variables.",
        "icesmp_identity_layout:",
        "  images:",
    ]
    for theme, faction_theme in FACTION_THEMES.items():
        faction_condition = (("theme", "icesmp_faction_theme", faction_theme),)
        image(identity, f"frame_{theme}", f"icesmp_frame_{theme}", -218, 18, 0,
              faction_condition, scale=0.30)
    for class_id in CLASSES:
        image(identity, f"class_{class_id}", f"icesmp_class_{class_id}", -200, 38, 3,
              (("class", "icesmp_class_id", class_id),), scale=0.46)
    image(identity, "money_icon", "icesmp_icon_money", -92, 55, 3, scale=0.23)
    image(identity, "level_icon", "icesmp_icon_level", -74, 39, 3, scale=0.23)
    identity += ["  texts:"]
    text(identity, 1,
         "<#[string:icesmp_faction_accent]><b>[string:icesmp_class_name]</b> <#A9B7C6>[string:icesmp_class_spec_name]",
         -166, 39, 0.48)
    text(identity, 2, "<#[string:icesmp_faction_accent]>[string:icesmp_faction]",
         -166, 55, 0.39)
    text(identity, 3, "<#D6A74B>[string:icesmp_balance]", -74, 55, 0.37)
    text(identity, 4, "<#71809A>Lv. <#FFFFFF>[string:icesmp_class_level]", -54, 39, 0.37)

    resource = [
        "# GENERATED by scripts/generate_betterhud_layout.py; edit the generator, not this file.",
        "icesmp_resource_layout:",
        "  images:",
    ]
    image(resource, "resource_track", "icesmp_resource_track", -166, 72, 1, scale=0.45)
    image(resource, "resource_fill", "icesmp_resource_fill", -166, 72, 2,
          color_overrides=(("red", "#E7683F", "icesmp_faction_id", "RED"),
                           ("blue", "#8BE9FD", "icesmp_faction_id", "BLUE"),
                           ("neutral", "#D6A74B", "icesmp_faction_id", "NEUTRAL"),
                           ("dark", "#62D7CE", "icesmp_faction_id", "DARK")), scale=0.45)
    resource += ["  texts:"]
    text(resource, 1,
         "<#C7D4EA>[string:icesmp_resource_name] <#FFFFFF>[string:icesmp_resource_current]<#75819A>//[string:icesmp_resource_max]",
         -166, 68, 0.36)

    world = [
        "# GENERATED by scripts/generate_betterhud_layout.py; edit the generator, not this file.",
        "icesmp_world_layout:",
        "  images:",
    ]
    image(world, "event_icon", "icesmp_icon_event", -198, 130, 3, scale=0.23)
    world += ["  texts:"]
    text(world, 1, "<#71809A>ESEMENY <#F0D88D>[string:icesmp_event]", -178, 133, 0.36)

    mechanic = [
        "# GENERATED by scripts/generate_betterhud_layout.py; edit the generator, not this file.",
        "icesmp_mechanic_layout:",
        "  images:",
    ]

    slot_x = [-198, -178, -158, -138, -118, -98, -78, -58]
    for slot, x in enumerate(slot_x, start=1):
        state_key = f"icesmp_class_slot_{slot}_state"
        kind_key = f"icesmp_class_slot_{slot}_kind"
        for kind in ("blood", "frost", "death"):
            for state in ("ready", "spent", "regenerating", "locked"):
                image(mechanic, f"rune_{slot}_{kind}_{state}", f"icesmp_rune_{kind}_{state}", x, 91, 5,
                      (("death_knight", "icesmp_class_id", "death_knight"),
                       ("kind", kind_key, kind), ("state", state_key, state)), scale=0.25)
        image(mechanic, f"rune_progress_{slot}", f"icesmp_rune_progress_{slot}", x + 2, 108, 6,
              (("death_knight", "icesmp_class_id", "death_knight"),
               ("regenerating", state_key, "regenerating")), scale=0.25)

    mechanic += ["  texts:"]
    text(mechanic, 1, "<#[string:icesmp_faction_accent]>[string:icesmp_class_mechanic_primary]",
         -198, 88, 0.38, (("not_dk", "icesmp_class_id", "death_knight", "!="),))
    text(mechanic, 2, "<#[string:icesmp_faction_accent_soft]>[string:icesmp_class_mechanic_secondary]",
         -105, 88, 0.35, (("not_dk", "icesmp_class_id", "death_knight", "!="),))
    text(mechanic, 3, "<#A9B7C6>[string:icesmp_class_state]",
         -198, 112, 0.34, (("not_dk", "icesmp_class_id", "death_knight", "!="),))
    text(mechanic, 4, "<#F4C96B>[string:icesmp_class_proc]",
         -105, 112, 0.34, (("not_dk", "icesmp_class_id", "death_knight", "!="),))
    text(mechanic, 5, "<#[string:icesmp_faction_accent]>[string:icesmp_class_mechanic_primary]",
         -198, 82, 0.35, (("death_knight", "icesmp_class_id", "death_knight"),))
    text(mechanic, 6, "<#A9B7C6>[string:icesmp_class_state] <#586781>| <#F4C96B>[string:icesmp_class_proc]",
         -198, 115, 0.32, (("death_knight", "icesmp_class_id", "death_knight"),))

    proc = [
        "# GENERATED by scripts/generate_betterhud_layout.py; edit the generator, not this file.",
        "# Compact proc toast, invoked by IceSMP through BetterHud's documented custom trigger.",
        "icesmp_class_proc_layout:",
        "  images:",
    ]
    for theme, faction_theme in FACTION_THEMES.items():
        faction_condition = (("theme", "icesmp_faction_theme", faction_theme),)
        image(proc, f"popup_{theme}", f"icesmp_popup_{theme}", -110, -22, 0,
              faction_condition, scale=0.75)
    for class_id in CLASSES:
        image(proc, f"class_{class_id}", f"icesmp_class_{class_id}", -92, -20, 3,
              (("class", "icesmp_class_id", class_id),), scale=0.5)
    proc += ["  texts:"]
    text(proc, 1, "<#[string:icesmp_faction_accent]><b>[string:icesmp_class_proc]</b>",
         -52, -13, 0.48)
    text(proc, 2, "<#A9B7C6>[string:icesmp_class_name]", -52, 0, 0.32)

    LAYOUT_DIR.mkdir(parents=True, exist_ok=True)
    outputs = {
        "icesmp-class-layout.yml": identity,
        "icesmp-resource-layout.yml": resource,
        "icesmp-world-layout.yml": world,
        "icesmp-mechanic-layout.yml": mechanic,
        "icesmp-proc-layout.yml": proc,
    }
    for file_name, content in outputs.items():
        (LAYOUT_DIR / file_name).write_text("\n".join(content) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
