#!/usr/bin/env python3
"""Generate the repetitive BetterHud 1.14.1 layout from the generic IceSMP HUD contract."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LAYOUT_DIR = ROOT / "deploy" / "betterhud" / "layouts"

FACTION_THEMES = {"guest": "ice", "red": "ember", "blue": "frost", "neutral": "guild", "dark": "lich"}
FACTION_COLORS = {"ice": "#77DDF2", "ember": "#E7683F", "frost": "#8BE9FD",
                  "guild": "#D6A74B", "lich": "#62D7CE"}
CLASSES = ("warrior", "evoker", "archer", "shaman", "monk", "paladin", "demon_hunter",
           "druid", "priest", "death_knight", "assassin", "warlock", "wizard")

# BetterHud 1.14.1 renders dynamic text/listener rows from a separate action-bar
# component origin than the static frame/header images when the HUD is anchored at
# gui.x=100. Keep that implementation offset in one place so every dynamic row
# stays on the 204 px panel canvas instead of forming a second block to its left.
PANEL_CONTENT_X = 170


def panel_x(x):
    return x + PANEL_CONTENT_X


def condition(name, placeholder, value, operation="==", kind="string", indent=6):
    pad = " " * indent
    second = f'"\'{value}\'"' if kind == "string" else str(value)
    return [f"{pad}{name}:", f'{pad}  first: "{kind}:{placeholder}"',
            f'{pad}  second: {second}', f'{pad}  operation: "{operation}"']


def image(lines, key, name, x, y, layer, conditions=(), color_overrides=(), scale=None):
    lines += [f"    {key}:", f"      name: {name}", f"      x: {x}", f"      y: {y}", f"      layer: {layer}"]
    if scale is not None:
        lines.append(f"      scale: {scale}")
    if color_overrides:
        lines.append("      color-overrides:")
        for override, color, placeholder, value in color_overrides:
            lines += [f"        {override}:", f'          color: "{color}"',
                      f'          first: "string:{placeholder}"', f'          second: "\'{value}\'"',
                      '          operation: "=="']
    if conditions:
        lines.append("      conditions:")
        for args in conditions:
            lines += condition(*args, indent=8)


def text(lines, index, pattern, x, y, scale, conditions=()):
    lines += [f"    {index}:", "      name: icesmp_class_font", f'      pattern: "{pattern}"',
              f"      x: {x}", f"      y: {y}", f"      scale: {scale}", "      align: left",
              "      layer: 7", "      outline: true", "      use-legacy-format: false"]
    if conditions:
        lines.append("      conditions:")
        for args in conditions:
            lines += condition(*args, indent=8)


def main():
    main_layout = [
        "# GENERATED by scripts/generate_betterhud_layout.py; edit the generator, not this file.",
        "# One shared canvas keeps every module on the exact same BetterHud origin.",
        "# It consumes only immutable IceSMP snapshot variables.",
        "icesmp_main_layout:",
        "  images:",
    ]
    for theme, faction_theme in FACTION_THEMES.items():
        faction_condition = (("theme", "icesmp_faction_theme", faction_theme),)
        image(main_layout, f"frame_{theme}", f"icesmp_frame_{theme}", -218, 18, 1,
              faction_condition, scale=1.0)
    for class_id in CLASSES:
        image(main_layout, f"class_{class_id}", f"icesmp_class_{class_id}", -200, 38, 5,
              (("class", "icesmp_class_id", class_id),), scale=0.46)
    image(main_layout, "money_icon", "icesmp_icon_money", -92, 55, 5, scale=0.23)
    image(main_layout, "level_icon", "icesmp_icon_level", -74, 39, 5, scale=0.23)
    image(main_layout, "resource_track", "icesmp_resource_track", panel_x(-166), 72, 2, scale=0.45)
    image(main_layout, "resource_fill", "icesmp_resource_fill", panel_x(-166), 72, 3,
          color_overrides=(("red", "#E7683F", "icesmp_faction_id", "RED"),
                           ("blue", "#8BE9FD", "icesmp_faction_id", "BLUE"),
                           ("neutral", "#D6A74B", "icesmp_faction_id", "NEUTRAL"),
                           ("dark", "#62D7CE", "icesmp_faction_id", "DARK")), scale=0.45)
    image(main_layout, "event_icon", "icesmp_icon_event", panel_x(-198), 130, 5, scale=0.23)

    not_death_knight = (("not_dk", "icesmp_class_id", "death_knight", "!="),)
    faction_colors = tuple((theme, color, "icesmp_faction_theme", theme)
                           for theme, color in FACTION_COLORS.items())
    for channel, x in (("primary", -198), ("secondary", -105)):
        visible = not_death_knight + (("numeric", f"icesmp_class_metric_{channel}_max", 0, ">", "number"),)
        image(main_layout, f"metric_{channel}_track", "icesmp_metric_track", panel_x(x), 101, 3,
              visible, scale=0.45)
        image(main_layout, f"metric_{channel}_fill", f"icesmp_metric_{channel}_fill", panel_x(x), 101, 4,
              visible, color_overrides=faction_colors, scale=0.45)

    semantic_colors = {
        "tertiary": (("element_fire", "#E7683F", "icesmp_class_metric_tertiary_state", "fire"),),
        "quaternary": (("element_frost", "#8BE9FD", "icesmp_class_metric_quaternary_state", "frost"),),
        "quinary": (("element_arcane", "#A08CC8", "icesmp_class_metric_quinary_state", "arcane"),),
    }
    for channel, x in (("tertiary", -198), ("quaternary", -151), ("quinary", -104)):
        visible = not_death_knight + (("numeric", f"icesmp_class_metric_{channel}_max", 0, ">", "number"),)
        image(main_layout, f"metric_{channel}_track", "icesmp_metric_mini_track", panel_x(x), 120, 3,
              visible, scale=0.40)
        image(main_layout, f"metric_{channel}_fill", f"icesmp_metric_{channel}_fill", panel_x(x), 120, 4,
              visible, color_overrides=semantic_colors[channel] + faction_colors, scale=0.40)

    for slot, x in enumerate(range(-198, -108, 10), start=1):
        state_key = f"icesmp_class_slot_{slot}_state"
        image(main_layout, f"charge_{slot}_ready", "icesmp_charge_ready", panel_x(x), 109, 5,
              not_death_knight + (("state", state_key, "ready"),),
              color_overrides=faction_colors, scale=0.25)
        image(main_layout, f"charge_{slot}_spent", "icesmp_charge_spent", panel_x(x), 109, 5,
              not_death_knight + (("state", state_key, "spent"),), scale=0.25)

    slot_x = [-198, -178, -158, -138, -118, -98, -78, -58]
    for slot, x in enumerate(slot_x, start=1):
        state_key = f"icesmp_class_slot_{slot}_state"
        kind_key = f"icesmp_class_slot_{slot}_kind"
        for kind in ("blood", "frost", "death"):
            for state in ("ready", "spent", "regenerating", "locked"):
                image(main_layout, f"rune_{slot}_{kind}_{state}", f"icesmp_rune_{kind}_{state}", panel_x(x), 91, 5,
                      (("death_knight", "icesmp_class_id", "death_knight"),
                       ("kind", kind_key, kind), ("state", state_key, state)), scale=0.25)
        image(main_layout, f"rune_progress_{slot}", f"icesmp_rune_progress_{slot}", panel_x(x + 2), 108, 6,
              (("death_knight", "icesmp_class_id", "death_knight"),
               ("regenerating", state_key, "regenerating")), scale=0.25)

    main_layout += ["  texts:"]
    text(main_layout, 1,
         "<#[string:icesmp_faction_accent]><b>[string:icesmp_class_name]</b> <#A9B7C6>[string:icesmp_class_spec_name]",
         panel_x(-166), 39, 0.48)
    text(main_layout, 2, "<#[string:icesmp_faction_accent]>[string:icesmp_faction]",
         panel_x(-166), 55, 0.39)
    text(main_layout, 3, "<#D6A74B>[string:icesmp_balance]", panel_x(-74), 55, 0.37)
    text(main_layout, 4, "<#71809A>Lv. <#FFFFFF>[string:icesmp_class_level]", panel_x(-54), 39, 0.37)
    text(main_layout, 5,
         "<#C7D4EA>[string:icesmp_resource_name] <#FFFFFF>[string:icesmp_resource_current]<#75819A>//[string:icesmp_resource_max]",
         panel_x(-166), 68, 0.36)
    text(main_layout, 6, "<#71809A>ESEMENY <#F0D88D>[string:icesmp_event]", panel_x(-178), 133, 0.36)
    text(main_layout, 7, "<#[string:icesmp_faction_accent]>[string:icesmp_class_mechanic_primary]",
         panel_x(-198), 88, 0.30, (("not_dk", "icesmp_class_id", "death_knight", "!="),))
    text(main_layout, 8, "<#[string:icesmp_faction_accent_soft]>[string:icesmp_class_mechanic_secondary]",
         panel_x(-105), 88, 0.29, (("not_dk", "icesmp_class_id", "death_knight", "!="),))
    text(main_layout, 9, "<#A9B7C6>[string:icesmp_class_state] <#F4C96B>[string:icesmp_class_proc]",
         panel_x(-105), 111, 0.27,
         (("not_dk", "icesmp_class_id", "death_knight", "!="),
          ("simple", "icesmp_class_metric_count", 2, "<=", "number")))
    text(main_layout, 10, "<#E7683F>[string:icesmp_class_metric_tertiary_label] <#FFFFFF>[string:icesmp_class_metric_tertiary_text]",
         panel_x(-198), 109, 0.22,
         (("not_dk", "icesmp_class_id", "death_knight", "!="),
          ("visible", "icesmp_class_metric_tertiary_max", 0, ">", "number")))
    text(main_layout, 13, "<#8BE9FD>[string:icesmp_class_metric_quaternary_label] <#FFFFFF>[string:icesmp_class_metric_quaternary_text]",
         panel_x(-151), 109, 0.22,
         (("not_dk", "icesmp_class_id", "death_knight", "!="),
          ("visible", "icesmp_class_metric_quaternary_max", 0, ">", "number")))
    text(main_layout, 14, "<#A08CC8>[string:icesmp_class_metric_quinary_label] <#FFFFFF>[string:icesmp_class_metric_quinary_text]",
         panel_x(-104), 109, 0.22,
         (("not_dk", "icesmp_class_id", "death_knight", "!="),
          ("visible", "icesmp_class_metric_quinary_max", 0, ">", "number")))
    text(main_layout, 11, "<#[string:icesmp_faction_accent]>[string:icesmp_class_mechanic_primary]",
         panel_x(-198), 82, 0.35, (("death_knight", "icesmp_class_id", "death_knight"),))
    text(main_layout, 12, "<#A9B7C6>[string:icesmp_class_state] <#586781>| <#F4C96B>[string:icesmp_class_proc]",
         panel_x(-198), 115, 0.32, (("death_knight", "icesmp_class_id", "death_knight"),))

    proc = [
        "# GENERATED by scripts/generate_betterhud_layout.py; edit the generator, not this file.",
        "# Compact proc toast, invoked by IceSMP through BetterHud's documented custom trigger.",
        "icesmp_class_proc_layout:",
        "  images:",
    ]
    for theme, faction_theme in FACTION_THEMES.items():
        faction_condition = (("theme", "icesmp_faction_theme", faction_theme),)
        image(proc, f"popup_{theme}", f"icesmp_popup_{theme}", -110, -22, 0,
              faction_condition, scale=0.75)
    for class_id in CLASSES:
        image(proc, f"class_{class_id}", f"icesmp_class_{class_id}", -92, -20, 3,
              (("class", "icesmp_class_id", class_id),), scale=0.5)
    proc += ["  texts:"]
    text(proc, 1, "<#[string:icesmp_faction_accent]><b>[string:icesmp_class_proc]</b>",
         -52, -13, 0.48)
    text(proc, 2, "<#A9B7C6>[string:icesmp_class_name]", -52, 0, 0.32)

    LAYOUT_DIR.mkdir(parents=True, exist_ok=True)
    outputs = {
        "icesmp-main-layout.yml": main_layout,
        "icesmp-proc-layout.yml": proc,
    }
    for legacy_name in ("icesmp-class-layout.yml", "icesmp-resource-layout.yml",
                        "icesmp-world-layout.yml", "icesmp-mechanic-layout.yml"):
        (LAYOUT_DIR / legacy_name).unlink(missing_ok=True)
    for file_name, content in outputs.items():
        (LAYOUT_DIR / file_name).write_text("\n".join(content) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
