package hu.taliann.icesmp.integrity;

public enum RewardChannel {
    KILL_REWARD, VANILLA_DROPS, VANILLA_XP, CUSTOM_LOOT, TRACKING_PROGRESS, QUEST_PROGRESS, QUEST_REWARD,
    PROFESSION_XP, RARE_GATHERING, CLASS_XP, PET_XP, COMMUNITY_GOAL, WEEKLY_GOAL, SERVER_CHALLENGE,
    BESTIARY, ACHIEVEMENT, DISCOVERY, CURRENCY_FAUCET, ITEM_ACQUISITION, PERSONAL_LOOT, CRATE_REWARD,
    DEV_ITEM_REWARD, PARKOUR_CREDIT, RAID_CREDIT, WAR_CREDIT, EVENT_REWARD
}
